# Generated by Django 2.2.6 on 2020-07-24 09:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200724_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='rules',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
